-- Hiển thị các lớp chứng chỉ
CREATE OR ALTER PROCEDURE HIEN_THI_LOP_CHUNG_CHI @ID_HV NVARCHAR(10)
AS
BEGIN
	DECLARE @LOAI_CC NVARCHAR(10)
	SELECT @LOAI_CC = HVLCC.Loai_chung_chi FROM Hoc_vien_lop_chung_chi HVLCC WHERE HVLCC.Id_hv = @ID_HV
	IF @LOAI_CC = 'CC A'
	BEGIN
		SELECT * FROM Mon_hoc MH WHERE MH.ID_hp = 'HP10004' AND MH.IsOpen = 1;
	END

	ELSE IF @LOAI_CC = 'CC B'
	BEGIN
		SELECT * FROM Mon_hoc MH WHERE MH.ID_hp = 'HP10009' AND MH.IsOpen = 1;
	END
END
GO

-- Đăng ký chứng chỉ
CREATE OR ALTER PROCEDURE DANG_KY_CHUNG_CHI @ID_HV NVARCHAR(10),
												@LOAI_CC NVARCHAR(10),
												@FLAG INT OUT
AS
BEGIN
	SET @FLAG = -1
	IF EXISTS(SELECT 1 FROM Hoc_vien_lop_chung_chi HVLCC WHERE HVLCC.Id_hv = @ID_HV)
	BEGIN
		SET @FLAG = 0;
		RETURN
	END

	ELSE
	BEGIN
		INSERT INTO Hoc_vien_lop_chung_chi VALUES (@ID_HV, @LOAI_CC)
		SET @FLAG = 1;
	END
END
GO

-- Đăng ký lớp chứng chỉ
CREATE OR ALTER PROCEDURE DANG_KY_LOP_CHUNG_CHI @ID_HV NVARCHAR(10),
												@ID_MH NVARCHAR(10),
												@FLAG INT OUT
AS
BEGIN
	SET @FLAG = -1
	IF EXISTS(SELECT 1 FROM DKMH_CC DKCC WHERE DKCC.Id_hv = @ID_HV AND DKCC.Id_mh = @ID_MH)
	BEGIN
		SET @FLAG = 0
		RETURN
	END

	ELSE
	BEGIN
		DECLARE @MA_GV NVARCHAR(10)
		SELECT @MA_GV = MH.ID_nv FROM Mon_hoc MH WHERE @ID_MH = MH.Id_mh
		INSERT INTO DKMH_CC VALUES (@ID_MH, @MA_GV, @ID_HV, 0)
		SET @FLAG = 1;
	END
END
GO

-- Hiển thị các lớp kỹ thuật
CREATE OR ALTER PROCEDURE HIEN_THI_LOP_KY_THUAT @ID_HV NVARCHAR(10)
AS
BEGIN
	
	SELECT * FROM Mon_hoc MH WHERE MH.IsOpen = 1
END
GO

-- Đăng ký học viên kỹ thuật
CREATE OR ALTER PROCEDURE DANG_KY_KY_THUAT @ID_HV NVARCHAR(10),
										   @FLAG INT OUT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM Hoc_vien_lop_ky_thuat HVLKT WHERE HVLKT.Id_hv = @ID_HV)
	BEGIN
		SET @FLAG = 1;
		RETURN
	END
	ELSE
	BEGIN
		INSERT INTO Hoc_vien_lop_ky_thuat VALUES (@ID_HV, 0)
	END
END
GO

-- Đăng ký lớp kỹ thuật
CREATE OR ALTER PROCEDURE DANG_KY_LOP_KY_THUAT @ID_HV NVARCHAR(10),
											   @ID_MH NVARCHAR(10),
											   @FLAG INT OUT
AS
BEGIN
	SET @FLAG = -1
	IF EXISTS(SELECT 1 FROM DKMH_KT DKKT WHERE DKKT.Id_hv = @ID_HV AND DKKT.Id_mh = @ID_MH)
	BEGIN
		SET @FLAG = 0
		RETURN
	END

	ELSE
	BEGIN
		DECLARE @MA_GV NVARCHAR(10)
		SELECT @MA_GV = MH.ID_nv FROM Mon_hoc MH WHERE @ID_MH = MH.Id_mh
		INSERT INTO DKMH_KT VALUES (@ID_MH, @MA_GV, @ID_HV, 0, 0)
		SET @FLAG = 1
	END
END
GO

-- Đăng ký tốt nghiệp
CREATE OR ALTER PROCEDURE DANG_KY_TOT_NGHIEP @ID_HV NVARCHAR(10),
											 @FLAG INT OUT
AS
BEGIN
	SET @FLAG = -2
	IF NOT EXISTS(SELECT 1 FROM DKMH_KT DKMHKT WHERE DKMHKT.Id_hv = @ID_HV)
	BEGIN
		SET @FLAG = -1
		RETURN;
	END
	IF EXISTS(SELECT 1 FROM Hoc_vien_tot_nghiep HVTN WHERE HVTN.Id_hv = @ID_HV)
	BEGIN
		SET @FLAG = 0
		RETURN
	END
	ELSE
	BEGIN
		DECLARE @SO_TIN_CHI NVARCHAR(10)
		SELECT @SO_TIN_CHI = HVLKT.So_hp_da_hoan_thanh FROM Hoc_vien_lop_ky_thuat HVLKT WHERE HVLKT.Id_hv = @ID_HV
		IF @SO_TIN_CHI >= 12
		BEGIN
			INSERT INTO Hoc_vien_tot_nghiep VALUES (@ID_HV, NULL, NULL)
		END
		ELSE
		BEGIN
			SET @FLAG = 1;
		END
	END
END
GO

---- Đăng ký thi lại
--CREATE OR ALTER PROCEDURE DANG_KY_THI_LAI @ID_HV NVARCHAR(10),
--										  @ID_MH NVARCHAR(10)
--AS
--BEGIN
--	DECLARE @SO_LAN_HOC_LAI INT
--	SELECT @SO_LAN_HOC_LAI = DKKT.So_lan_thi_lai FROM DKMH_KT DKKT WHERE DKKT.Id_hv = @ID_HV AND DKKT.Id_mh = @ID_MH 

--	IF @SO_LAN_HOC_LAI >= 3
--	BEGIN
--		RETURN
--	END

--	ELSE
--	BEGIN
--		UPDATE DKMH_KT SET Diem_mon_hoc = 0 WHERE Id_hv = @ID_HV AND Id_mh = Id_mh
--		SET @SO_LAN_HOC_LAI = @SO_LAN_HOC_LAI + 1
--		UPDATE DKMH_KT SET So_lan_thi_lai = @SO_LAN_HOC_LAI WHERE Id_hv = @ID_HV AND Id_mh = Id_mh
--	END
--END